apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-calculator-deployment
spec:
  replicas: 3  # Number of desired replicas
  selector:
    matchLabels:
      app: flask-calculator
  template:
    metadata:
      labels:
        app: flask-calculator
    spec:
      containers:
      - name: flask-calculator
        image: teebro/ci-cd-jenkins-argocd:5
        ports:
        - containerPort: 8000  # Port your Flask app is listening on

---
apiVersion: v1
kind: Service
metadata:
  name: flask-calculator-service
spec:
  type: LoadBalancer
  selector:
    app: flask-calculator
  ports:
  - protocol: TCP
    port: 80  # Port to expose on the LoadBalancer
    targetPort: 8000  # Your Flask app is listening on

protocol: TCP
    port: 80  # Port to expose on the LoadBalancer
    targetPort: 8000  # Your Flask app is listening on
