apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-calculator-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-calculator
  template:
    metadata:
      labels:
        app: flask-calculator
    spec:
      containers:
      - name: flask-calculator
        image: teebro/ci-cd-jenkins-argocd:31
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: flask-calculator-service
spec:
  type: LoadBalancer
  selector:
    app: flask-calculator
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
